### ISSUE TITLE
Добавить jsDoc

### ISSUE THREAD

**Issue by vkhv** [SporYo/calculateDeposit#2]
Доку из readme нужно портировать в код в формате  jsDoc.
Смотри примеры тут https://ru.wikipedia.org/wiki/JSDoc

**Comment by SporYo** [comment]
https://github.com/SporYo/calculateDeposit/commits/master

**Comment by vkhv** [comment]
ab09f7b83749d0bb458f6cf0d235fd951e26f662

**Comment by SporYo** [comment]
ab09f7b83749d0bb458f6cf0d235fd951e26f662

**Comment by SporYo** [comment]
ab09f7b83749d0bb458f6cf0d235fd951e26f662
